### List all users
GET http://127.0.0.1:3000/api/user/allUsers

### Register user
POST http://127.0.0.1:3000/api/user/register
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "Password123!"
}


### List all products
GET http://127.0.0.1:3000/products

### List all orders
GET http://127.0.0.1:3000/orders

### List all carts
GET http://127.0.0.1:3000/carts
